-- Enable UUID extension (optional but good practice)
-- create extension if not exists "uuid-ossp";

-- Table: game_states
CREATE TABLE IF NOT EXISTS game_states (
    channel_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    language TEXT NOT NULL,
    current_word TEXT NOT NULL,
    current_player_id BIGINT NOT NULL,
    used_words JSONB NOT NULL DEFAULT '[]'::jsonb,
    players JSONB NOT NULL DEFAULT '[]'::jsonb,
    turn_count INTEGER DEFAULT 0,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    is_bot_challenge BOOLEAN DEFAULT FALSE,
    turn_start_time FLOAT DEFAULT 0,
    wrong_attempts INTEGER DEFAULT 0,
    scores JSONB DEFAULT '{}'::jsonb
);

-- Table: player_stats
CREATE TABLE IF NOT EXISTS player_stats (
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    total_points BIGINT DEFAULT 0,
    games_played INTEGER DEFAULT 0,
    words_submitted INTEGER DEFAULT 0,
    correct_words INTEGER DEFAULT 0,
    wrong_words INTEGER DEFAULT 0,
    longest_word TEXT DEFAULT '',
    longest_word_length INTEGER DEFAULT 0,
    last_played TIMESTAMPTZ DEFAULT NOW(),
    last_daily_claim TIMESTAMPTZ,
    daily_streak INTEGER DEFAULT 0,
    last_daily_reward INTEGER DEFAULT 0,
    PRIMARY KEY (user_id, guild_id)
);

-- Table: game_history
CREATE TABLE IF NOT EXISTS game_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    language TEXT NOT NULL,
    winner_id BIGINT,
    total_turns INTEGER DEFAULT 0,
    total_words INTEGER DEFAULT 0,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: channel_configs
CREATE TABLE IF NOT EXISTS channel_configs (
    channel_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    game_type TEXT NOT NULL
);

-- Table: fishing_inventory
CREATE TABLE IF NOT EXISTS fishing_inventory (
    user_id BIGINT PRIMARY KEY,
    rod_type TEXT DEFAULT 'Plastic Rod',
    boat_type TEXT DEFAULT 'None',
    inventory JSONB DEFAULT '{}'::jsonb,
    upgrades JSONB DEFAULT '{}'::jsonb,
    stats JSONB DEFAULT '{}'::jsonb,
    last_fished TIMESTAMPTZ
);
